project:
  type: website
  output-dir: _site

website:
  title: "Industry Studies Association"
  sidebar:
    logo: logo.webp
    style: "docked"
    background: primary
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: mission.qmd
        text: Mission Statement
      - section: "Conference"
        contents:
          - href: conference.qmd
            text: Call for Papers
          - href: submissions.qmd
            text: Submission Guidelines
      - href: awards.qmd
        text: Awards

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
