project:
  type: website
  output-dir: _site

website:
  title: "Industry Studies Association"
  sidebar:
    logo: logo.webp
    style: "docked"
    background: primary
    contents:
      - href: index.qmd
        text: Home
      - href: conference.qmd
        text: 2026 Conference
      - href: about.qmd
        text: About
      - href: mission.qmd
        text: Mission Statement

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
